name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (ci)
        run: npm ci
        continue-on-error: true

      - name: Install dependencies (fallback)
        run: npm i

      - name: Lint
        run: npx eslint . --ext .ts,.tsx --max-warnings=0 || echo "Lint finished"

      - name: Build
        run: npm run build
